# Generated by Django 5.2.7 on 2026-05-03 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructuur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infrastructuur_id', models.CharField(max_length=50, unique=True)),
                ('naam', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('locatie', models.CharField(max_length=150)),
                ('status', models.CharField(blank=True, default='actief', max_length=150)),
                ('beheerder', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meetparameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=32)),
                ('eenheid', models.CharField(max_length=10)),
                ('drempel_onder', models.FloatField()),
                ('drempel_boven', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_id', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('spanningsniveau', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Meting',
            fields=[
                ('meting_id', models.AutoField(primary_key=True, serialize=False)),
                ('tijdstip', models.DateTimeField()),
                ('waarde', models.FloatField()),
                ('kwaliteit', models.CharField(default='in_spec', max_length=20)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metingen', to='monitoring.meetparameter')),
            ],
        ),
        migrations.CreateModel(
            name='Afwijking',
            fields=[
                ('afwijking_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('omschrijving', models.CharField(max_length=200)),
                ('duur', models.FloatField(blank=True, null=True)),
                ('begintijd', models.DateTimeField(blank=True, null=True)),
                ('eindtijd', models.DateTimeField(blank=True, null=True)),
                ('meting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afwijkingen', to='monitoring.meting')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=150, unique=True)),
                ('type', models.CharField(max_length=32)),
                ('communicatie_protocol', models.CharField(default='NB-IoT', max_length=32)),
                ('status', models.CharField(default='actief', max_length=32)),
                ('infrastructuur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensoren', to='monitoring.infrastructuur')),
                ('net', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensoren', to='monitoring.net')),
            ],
        ),
        migrations.CreateModel(
            name='Netbelasting',
            fields=[
                ('netbelasting_id', models.AutoField(primary_key=True, serialize=False)),
                ('tijdstip_meting', models.DateTimeField()),
                ('spanning', models.FloatField(blank=True, null=True)),
                ('frequentie', models.FloatField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='netbelastingen', to='monitoring.sensor')),
            ],
        ),
        migrations.AddField(
            model_name='meting',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metingen', to='monitoring.sensor'),
        ),
    ]
