# Generated by Django 5.2.7 on 2026-05-05 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medewerker_id', models.CharField(max_length=50, unique=True)),
                ('naam', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('beheerder', 'Beheerder'), ('technicus', 'Technicus'), ('monitor', 'Monitor')], max_length=50)),
                ('emailadres', models.EmailField(max_length=254)),
                ('telefoonnummer', models.CharField(blank=True, max_length=20)),
                ('actief', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'operator',
                'verbose_name_plural': 'operators',
            },
        ),
        migrations.AlterModelOptions(
            name='afwijking',
            options={'verbose_name_plural': 'Afwijkingen'},
        ),
        migrations.AlterModelOptions(
            name='infrastructuur',
            options={'verbose_name_plural': 'Infrastructuren'},
        ),
        migrations.AlterModelOptions(
            name='meetparameter',
            options={'verbose_name_plural': 'Meetparameters'},
        ),
        migrations.AlterModelOptions(
            name='meting',
            options={'verbose_name_plural': 'Metingen'},
        ),
        migrations.AlterModelOptions(
            name='net',
            options={'verbose_name_plural': 'Netten'},
        ),
        migrations.AlterModelOptions(
            name='netbelasting',
            options={'verbose_name_plural': 'Netbelastingen'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name_plural': 'Sensoren'},
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapport_id', models.CharField(max_length=50, unique=True)),
                ('titel', models.CharField(max_length=200)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
                ('periode_start', models.DateTimeField()),
                ('periode_einde', models.DateTimeField()),
                ('inhoud', models.TextField()),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.operator')),
            ],
            options={
                'verbose_name': 'rapport',
                'verbose_name_plural': 'rapporten',
            },
        ),
    ]
