# Generated by Django 5.2.7 on 2026-05-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_operator_alter_afwijking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='net',
            name='freq_max',
            field=models.FloatField(default=50.2),
        ),
        migrations.AddField(
            model_name='net',
            name='freq_min',
            field=models.FloatField(default=49.8),
        ),
    ]
