# Generated by Django 5.2.7 on 2026-05-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_net_freq_max_net_freq_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='net',
            name='freq_max',
            field=models.FloatField(default=50.01),
        ),
        migrations.AlterField(
            model_name='net',
            name='freq_min',
            field=models.FloatField(default=49.99),
        ),
    ]
