# Generated by Django 5.2.7 on 2026-05-07 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_net_freq_max_alter_net_freq_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afwijking',
            name='meting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='afwijkingen', to='monitoring.meting'),
        ),
        migrations.AlterField(
            model_name='meting',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metingen', to='monitoring.meetparameter'),
        ),
        migrations.AlterField(
            model_name='meting',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metingen', to='monitoring.sensor'),
        ),
        migrations.AlterField(
            model_name='netbelasting',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='netbelastingen', to='monitoring.sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='infrastructuur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensoren', to='monitoring.infrastructuur'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='net',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensoren', to='monitoring.net'),
        ),
    ]
