# Generated by Django 5.2.7 on 2026-05-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_afwijking_meting_alter_meting_parameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='net',
            name='freq_max',
            field=models.FloatField(default=50.5),
        ),
        migrations.AlterField(
            model_name='net',
            name='freq_min',
            field=models.FloatField(default=49.5),
        ),
    ]
