# Generated by Django 5.2.7 on 2026-05-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_net_freq_max_alter_net_freq_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sensor',
            name='region',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sensor',
            name='station',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
