# Generated by Django 5.2.7 on 2026-05-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_sensor_location_sensor_region_sensor_station'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meting',
            options={'ordering': ['-tijdstip'], 'verbose_name_plural': 'Metingen'},
        ),
        migrations.AddField(
            model_name='meting',
            name='infeed_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meting',
            name='tijdstip',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
