# Generated by Django 5.2.7 on 2026-05-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_alter_meting_options_meting_infeed_value_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Afwijking',
        ),
    ]
