# Generated by Django 5.2.7 on 2026-05-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_delete_afwijking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Netbelasting',
        ),
    ]
