# Generated by Django 5.2.7 on 2026-05-22 15:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_delete_netbelasting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meting',
            name='infeed_value',
        ),
        migrations.AlterField(
            model_name='meetparameter',
            name='naam',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='meting',
            name='parameter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='metingen', to='monitoring.meetparameter'),
        ),
        migrations.AlterField(
            model_name='meting',
            name='sensor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='metingen', to='monitoring.sensor'),
        ),
        migrations.AlterField(
            model_name='meting',
            name='tijdstip',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
