# Generated by Django 5.2.7 on 2026-05-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_remove_meting_infeed_value_alter_meetparameter_naam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapport',
            name='operator',
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
    ]
