# Generated by Django 5.2.7 on 2026-05-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_remove_rapport_operator_delete_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='laatste_tijdstip',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='laatste_waarde',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
