# Generated by Django 5.2.7 on 2026-05-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_sensor_laatste_tijdstip_sensor_laatste_waarde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='communicatie_protocol',
        ),
    ]
