# Generated by Django 5.2.7 on 2026-05-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_remove_sensor_communicatie_protocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='region',
        ),
    ]
