# Generated by Django 5.2.7 on 2026-05-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_remove_sensor_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meting',
            name='kwaliteit',
        ),
    ]
