# Generated by Django 5.2.7 on 2026-05-24 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_remove_meting_kwaliteit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetparameter',
            name='drempel_boven',
        ),
        migrations.RemoveField(
            model_name='meetparameter',
            name='drempel_onder',
        ),
        migrations.RemoveField(
            model_name='meting',
            name='meting_id',
        ),
        migrations.AddField(
            model_name='meting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meting',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metingen', to='monitoring.meetparameter'),
        ),
        migrations.AlterField(
            model_name='meting',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metingen', to='monitoring.sensor'),
        ),
    ]
