# Generated by Django 5.2.7 on 2026-05-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_remove_meetparameter_drempel_boven_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='net',
            name='freq_max',
        ),
        migrations.RemoveField(
            model_name='net',
            name='freq_min',
        ),
    ]
